In [27]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import precision_score,f1_score,recall_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('../data/fashion-mnist_train.csv')
df.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=2)

In [15]:
X_train.shape

(48000, 784)

In [16]:
logistic_regression = LogisticRegression(max_iter=100000)
decision_tree = DecisionTreeClassifier()

In [17]:
logistic_regression.fit(X_train,y_train)
decision_tree.fit(X_train,y_train)

/opt/anaconda3/envs/machine_learning_env/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 13882 iteration(s) (status=1):
STOP: TOTAL NO. OF F,G EVALUATIONS EXCEEDS LIMIT

You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [19]:
y_pred1 = logistic_regression.predict(X_test)
y_pred2 = decision_tree.predict(X_test)

In [20]:

print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.8356666666666667
Accuracy of Decision Trees 0.794

In [22]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1))

Logistic Regression Confusion Matrix

     0     1    2     3    4     5    6     7     8     9
0  954    17   21    68    8     2  122     0    14     1
1    1  1184    5    22    6     0    5     0     4     0
2   23    18  889    16  143     0  102     0    14     2
3   50    35    9  1029   48     1   24     0     9     0
4    7     8  106    41  898     0   93     0    10     0
5    2     2    0     4    0  1092    1    46    12    58
6  168    11  118    54  111     1  671     0    35     0
7    0     2    0     1    0    45    0  1132     4    56
8   14     9   20    10   10    11   30     4  1062     2
9    0     2    0     2    1    25    3    40     3  1117

In [23]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2))

Decision Tree Confusion Matrix

     0     1    2    3    4     5    6     7     8     9
0  910     5   21   47   15     3  196     0    10     0
1    6  1170    4   27    4     2    9     0     5     0
2   29     3  794   21  181     1  154     1    21     2
3   49    37   24  976   62     0   43     1    10     3
4   17    13  162   60  781     1  115     2    11     1
5    5     1    3    6    2  1074    2    63    14    47
6  191     5  152   53  129     4  617     0    18     0
7    0     0    1    2    0    68    0  1074     4    91
8   19     5   17    9   14    18   20     9  1058     3
9    1     0    3    2    4    25    4    75     5  1074

In [24]:

precision_score(y_test,y_pred1,average='weighted')

0.8339102028194023

In [25]:
recall_score(y_test,y_pred1,average='weighted')

0.8356666666666667

In [26]:
f1_score(y_test,y_pred1,average='weighted')

0.8344087849189861

In [28]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.78      0.79      0.79      1207
           1       0.92      0.96      0.94      1227
           2       0.76      0.74      0.75      1207
           3       0.83      0.85      0.84      1205
           4       0.73      0.77      0.75      1163
           5       0.93      0.90      0.91      1217
           6       0.64      0.57      0.60      1169
           7       0.93      0.91      0.92      1240
           8       0.91      0.91      0.91      1172
           9       0.90      0.94      0.92      1193

    accuracy                           0.84     12000
   macro avg       0.83      0.83      0.83     12000
weighted avg       0.83      0.84      0.83     12000